# Generated by Django 5.0.7 on 2024-08-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_user_is_staff_alter_user_mpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
