# Generated by Django 5.0.7 on 2024-08-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_user_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
