# Generated by Django 5.0.7 on 2024-08-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_user_username_user_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_number',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
