# Generated by Django 5.0.7 on 2024-08-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_remove_user_account_number_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
