# Generated by Django 5.0.7 on 2024-08-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_account_debit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
    ]
