# Generated by Django 5.0.7 on 2024-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_remove_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='debit_card',
            field=models.BigIntegerField(),
        ),
    ]
