# Generated by Django 5.0.7 on 2024-08-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_user_city_id_user_gender'),
    ]

    operations = [
    ]
