# Generated by Django 5.0.7 on 2024-08-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20240825_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city_id',
            new_name='city',
        ),
    ]
