# Generated by Django 5.0.7 on 2024-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirm', 'confirm'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
