# Generated by Django 5.0.7 on 2024-09-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_creditcard_is_freeze_creditcard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='custom_name',
        ),
    ]
