# Generated by Django 5.0.7 on 2024-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_remove_report_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='used',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
