# Generated by Django 5.0.7 on 2024-10-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_transaction_is_rolled_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='upi_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
