# Generated by Django 5.0.7 on 2024-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_account_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='upi_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
