POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{ 
    "username":"faiz",
    "password":"faiz"
}


###

POST http://127.0.0.1:8000/api/verify_otp/
Content-Type: application/json

{
    "username":"faiz",
    "otp":"714832"
}

###
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
    "name":"faiz",
    "email":"faizrajput1510@outloo.com",
    "password":"faiz",
    "username":"faiz",
    "phone":"1234522699",
    "pan_card":"gjgpr2313k",
    "aadhar_card":"123456789012",
    "dob":"2024-5-14",
    "mpin":"123456",
    "type":"user"
}

###
POST http://127.0.0.1:8000/api/admin/transaction-statistics-self-debit-card/day/
Authorization: Token f7263bebd2b10da648603d87509183c7a980a6a1
Content-Type: application/json

{
    "receiver_id": 1,
    "amount": 500
}

###
GET http://127.0.0.1:8000/api/see-balance/
Authorization: Token 39ecd3fbed6db8c3cbc31af8bf2d7c49df9319d6
Content-Type: application/json


###
GET http://127.0.0.1:8000/api/transaction/
Authorization: Token 71751a90b5c7d34493f8ae124d3e3dd48537a19d
Content-Type: application/json

# this is admin apis
###
GET http://127.0.0.1:8000/api/user/
Authorization: Token 71751a90b5c7d34493f8ae124d3e3dd48537a19d
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/users/
Authorization: Token 71751a90b5c7d34493f8ae124d3e3dd48537a19d
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/user/1
Authorization: Token 71751a90b5c7d34493f8ae124d3e3dd48537a19d
Content-Type: application/json

